### ISSUE TITLE
Rename project to symfony-docker-edition

### ISSUE THREAD

**Issue by drgomesp** [drgomesp/symfony-docker#14]
I was thinking if we should rename the repository name to symfony-docker-edition. Thoughts?

**Comment by aferrandini** [comment]
I'm not sure this is a Symfony Docker Edition, this is just a Symfony app with a Docker configuration.
This configuration can be move to any project, even if is Symfony or not.

**Comment by drgomesp** [comment]
While I agree with you, I'd like to point out that this project started with the idea of being Symfony specific, therefore we would tweak every possible service to be fully optimised for the Symfony environment. However, if we would support multiple frameworks, the code base would change significantly, as well as some configuration such as virtual host and so on.
