### ISSUE TITLE
Docker-compose run composer install failed

### ISSUE THREAD

**Issue by neothone** [drgomesp/symfony-docker#15]
Hi,

On my Ubuntu and on my Mac OS X, the next command failed : 
`docker-compose run symfony-docker composer --prefer-source install`

Error message is "ERROR: No such service symfony-docker"

However the command `docker-compose ps` show three services (api-mariadb, api-memcached and symfony-docker).

**Comment by drgomesp** [comment]
I suggest you run composer from your local machine instead. However, I'll have a look and see why this could be failing.

**Comment by neothone** [comment]
Thank you for your suggest.

I try and it's work from my local machine. 

I attach here a screenshoot of my command line (Mac OS X) : 

<img width="671" alt="capture d ecran 2016-01-30 a 14 06 54" src="https://cloud.githubusercontent.com/assets/13251143/12695861/d177b26e-c75a-11e5-991d-3112d26b9d56.png">

**Comment by drgomesp** [comment]
Just to clarify, you should run:

``` bash
docker-compose run web composer --prefer-source install
```

Since the service name is web, and not symfony-docker.

**Comment by neothone** [comment]
I'm not sure...

Look this screenshoot, with "docker-compose run web" we work by default in directory /var/www/html

![capture d ecran 2016-01-30 a 15 52 30](https://cloud.githubusercontent.com/assets/13251143/12696378/abea192e-c769-11e5-9864-e723c7e63a03.png)

**Comment by drgomesp** [comment]
@mathieu-dumoutier I see your point. Solved by ccc4ce0.

**Comment by neothone** [comment]
Great ! Thank you !
