### ISSUE TITLE
Git, pdo and pdo_mysql are missing ?

### ISSUE THREAD

**Issue by Djamy** [drgomesp/symfony-docker#19]
Hello,

I do not know if I am alone in this case but this stack is not usable out of the box (tested on windows).
- Impossible to do a proper composer install because of git missing on the web image.
- When trying to connect to mariadb there is an error yelling that php could not find driver.

After adding git and installing pdo and pdo_mysql I was able to create my database with symfony's console. But, I still have permissions problems...

Did I do something wrong or missed something ? Or is this "normal" ?

Thanks.

**Comment by drgomesp** [comment]
Hello,

sorry for those problems you had. Could you please be more specific about how you're running the commands?

For example, the composer install should be like this:

``` bash
docker-compose run symfony-docker composer --prefer-source install
```

There's no Git dependency for Composer as far as I know.

Regarding pdo and pdo_mysql extensions, I'll take another look, but it should probably be just a matter of adding the extensions like you said – it's weird that I would forget those.

Please let me know if you still have more issues.

**Comment by Djamy** [comment]
Forget about Git.

However, the driver is actually missing and there is a small problem with memcached.so (its apparently missing from the folder where php-fpm read extensions or something..).

So I know that you can install pdo and pdo_mysql extensions by adding a `RUN docker-php-ext-install pdo pdo_mysql` in the Dockerfile.

**Comment by drgomesp** [comment]
That's not the ideal. I'll push soon the `pdo` and `pdo_mysql` extensions configuration so that this is really out of the box.

**Comment by Djamy** [comment]
We just need something functional and it's weird that no one has reported this before.. I really though that I did something wrong.

We wait for @mathewpeterson 's PR #13

**Comment by drgomesp** [comment]
It's solved.
