### ISSUE TITLE
dont expose db port

### ISSUE THREAD

**Issue by ivoba** [drgomesp/symfony-docker#21]
I run docker nativly on ubuntu and also have mysql running on the host.
When exposing the port 3306 of MariaDB this will collide with the host DB.

```
Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
```

So i propose to not expose the port but keep it internal:
by replacing:

```
ports:
   - "3306:3306"
```

to:

```
ports:
  - 3306
```

As the tutum image already allows remote connections by 

```
RUN sed -i -r 's/bind-address.*$/bind-address = 0.0.0.0/' /etc/mysql/my.cnf
```

its still possible to use f.e. workbench to check your database by using the ip as host.
You can get the ip of the container with:

```
docker inspect --format '{{ .NetworkSettings.IPAddress }} {{ .Name }}' $(docker ps -q)
```

**Comment by drgomesp** [comment]
It makes a lot of sense. Want to open a PR?
