### ISSUE TITLE
cache permission issue

### ISSUE THREAD

**Issue by ivoba** [drgomesp/symfony-docker#23]
I run the containers and did make the composer install but the permissions for the cache files are not properly set and i get:

```
Failed to write cache file "/app/var/cache/dev/classes.php".
```

This problem is one of the main painpoints of using symfony with docker, imho, at least in a dev env.
I've been struggling with that for a while now and maybe we can find a solution here together.

You can read my struggle here: https://stackoverflow.com/questions/34949083/symfony-docker-permission-problems-for-cache-files.

**Comment by drgomesp** [comment]
I don't have this problem on my environment.

How are you running composer install and cache-clear commands?

**Comment by ivoba** [comment]
i run

```
docker-compose run web composer --prefer-source install
```

cache:clear is run as post-install-cmd.

var/cache/dev is owned by root, probably because composer was executed as root, which is probably the default user when running 'docker-compose run'

**Comment by drgomesp** [comment]
You should try running both commands from outside of the container. Let me know if that works.

**Comment by ivoba** [comment]
Is 'docker-compose run web composer --prefer-source install' not outside of the container?

Do you mean running 'composer install' and 'app/console cache:clear' on the host?
This would use the host's php-cli and is not desired, imho.

**Comment by drgomesp** [comment]
I'm sorry then, I misunderstood what you said.

For me, running both commands with `docker-compose run` work just fine, which is very weird...

**Comment by ivoba** [comment]
Who owns your var/cache/dev dir?
And which user are you when entering the container?

```
docker exec -i -t symfony-docker /bin/bash
```

Maybe my docker is wrongly configured.

**Comment by drgomesp** [comment]
Basically I did a clean install and ran `composer install` from my dev machine instead of using docker-compose run, and everything worked fine. Can you confirm?

**Comment by ivoba** [comment]
Well yes this will work, because then your cache will be created by the host and then 

```
RUN usermod -u 1000 www-data 
```

will work.

However this has some downsides:
- you are depending on your hosts php-cli version
- you are depending on your hosts composer and the one in the Dockerfile is not needed
- when you have custom commands and you run them on the host they wont have access to linked containers
- when you have custom commands and run them inside the container they will have permission problems
- the inital docker-compose run web composer --prefer-source install would be wrong
- assets:install web --symlink will probably not work because the symlink is on the host

**Comment by drgomesp** [comment]
Just to clarify, I've just created a clean install and ran the cache clear command the same way you did. Here's the output:

``` bash
docker-compose run web composer --prefer-source install                            1 ↵
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- ----------------- ------------------
      Bundle            Method / Error
 --- ----------------- ------------------
  ✔   FrameworkBundle   relative symlink
 --- ----------------- ------------------


 [OK] All assets were successfully installed.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
```

**Comment by ivoba** [comment]
ok, looked the same here.
but then when opening the web frontend on http://localhost:8888 i got the error that cache is not writeable.
Failed to write cache file "/app/var/cache/dev/classes.php".

Because var/cache/dev was onwed by root.
Can you tell me the owner of your var/cache/dev please?

**Comment by drgomesp** [comment]
`drwxr-xr-x 1 www-data staff 306 Feb 15 12:32 dev`

**Comment by ivoba** [comment]
thats weird, how comes its not root owned?
they even mention this in the official docs that _docker-compose run_ is root:
https://docs.docker.com/compose/django/

> "The files django-admin created are owned by root. This happens because the container runs as the root user."

can anyone else confirm this? @henriquemoody @mathewpeterson
