### ISSUE TITLE
Error while clearing the cache

### ISSUE THREAD

**Issue by bolebon** [drgomesp/symfony-docker#29]
First of all, nice job for this Symfony Docker edition.
Then, I tried to clear symfony's cache by using this command:

`$ docker-compose run web php bin/console cache:clear`

But all I got is this error:

```
  [Symfony\Component\Filesystem\Exception\IOException]       
  Failed to remove directory "/app/var/cache/de~/doctrine".  


cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

I'm not sure if that's a real issue or if I'm doing it wrong...

**Comment by drgomesp** [comment]
Which version of the package are you using?

**Comment by bolebon** [comment]
I think I was using an old one.
So I've just downloaded the master but when I run the command:

`docker-compose run symfony-docker composer update`

I get this error:

`ERROR: No such service: web`

Which seems legit given that there is no "web" container in the docker-compose.yml.
I tried to replace "web" with "app" but composer does not seem to be installed in this container.

**Comment by drgomesp** [comment]
If you're using master, please refer to the [DockerBundle](https://github.com/drgomesp/SymfonyDockerBundle), which is the new way we will handle docker compose on this edition.

All you need is `console docker:run`

**Comment by bolebon** [comment]
Do you recommand me to use master ?
Because I took an eye to the DockerBundle and it does not seem to be finished. There's two issues opened by yourself and there isn't "docker:run" command in the bundle.
Wouldn't the 1.1.2 version be a better solution for the moment ?

**Comment by drgomesp** [comment]
Yes, I recommend the current stable version, which is `1.1.2` for now.

**Comment by drgomesp** [comment]
@Zioza can you provide a feedback regarding this? Did `1.1.2` work as expected for you?

**Comment by drgomesp** [comment]
@Zioza any feedback?
