### ISSUE TITLE
Unable to build due to incorrect path

### ISSUE THREAD

**Issue by rwslinkman** [drgomesp/symfony-docker#30]
I've converted my Symfony 2.6 project into the symfony-docker format today.
I wanted to run `php bin/console docker:compose:build` but I've got the following error.

```
ERROR: build path C:\Development\Code\Web\rwslinkman\vendor\drgomesp\symfony-docker-bundle\Resources\config\docker\vendor\symfony-docker\docker-bundle\Resources\config\docker\nginx
either does not exist, is not accessible, or is not a valid URL.

```

The command cannot find the config files because the path is incorrect. I've tried to look for a "relative path" setting but no luck.
Is there something I've missed in the configuration?

**Comment by drgomesp** [comment]
@rwslinkman sorry for taking long to respond.

Did you run `composer install` or `composer update`?

**Comment by rwslinkman** [comment]
@drgomesp No problem :)
I have indeed run `composer install`. After that, I have run `php bin/console docker:compose:build`

**Comment by drgomesp** [comment]
Awesome, I'm glad it works! I should probably add that to the docs.

Let me know if you need anything else.

**Comment by rwslinkman** [comment]
@drgomesp 
It's still not working. Sorry if I gave you the wrong impression.
I have been trying to change a few things, but still no luck.

**Comment by drgomesp** [comment]
I'm sorry, I got a bit confused.

Have you checked if the symlink is created correctly? There is a [command](https://github.com/drgomesp/SymfonyDockerBundle/blob/master/Composer/DockerCompose.php) from DockerBundle that is supposed to run on with composer and create a symlink to docker-compose file.

Can you check if that's the case?

**#EDIT:**

I've just realized you're on Windows. I'm pretty sure the command is not going to work there. We need to create a fallback command for Windows.

**Comment by rwslinkman** [comment]
I have not seen the command before but I think it will help.
How do I call this command?

Do I put the command in my `composer.json` under `scripts > post-install-cmd`?
Or do I run it via command line?
I was not able to find it via the link you provided.

**Comment by drgomesp** [comment]
That should run automatically, but it's not working because I forgot to push the change on the composer file. Let me do that tonight.

However, I still think this will probably need a fallback strategy on Windows.

**Comment by rwslinkman** [comment]
Alright, thanks for the info. I will wait for the new version to be pushed.

With respect to the fallback strategy for Windows: from what I see in Symfony, it copies the files it cannot create symlinks for. I see it in my console output all the time.

```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --------- ----------------- ----------------
            Bundle            Method / Error 
 --------- ----------------- ----------------
  WARNING   FrameworkBundle   copy
  WARNING   FrontEndBundle    copy
  WARNING   BackEndBundle     copy
 --------- ----------------- ----------------

 ! [NOTE] Some assets were installed via copy. If you make changes to these assets you have to run this command again.  
```

**Comment by rwslinkman** [comment]
@drgomesp Did you find the time to push the composer file?
I feel like I've missed it. Sorry to bother you on the weekend.

**Comment by rwslinkman** [comment]
@drgomesp Hi, sorry to bother you but could you finalize the issue please?
I'd like see my project running within docker :)

**Comment by drgomesp** [comment]
Hello @rwslinkman. I'm sorry for the long time without a reply. I'm too busy with life at the moment. Do you think you can open a PR with the fix?

**Comment by rwslinkman** [comment]
Thanks for letting me know, @drgomesp . I've never contributed to other projects than my own, but I'll give it a try!

**Comment by drgomesp** [comment]
Hey guys. I've reestructured this project a little bit, and now you don't require docker-bundle anymore. Just pull from this repo and run `docker-compose up` from main folder.
