### ISSUE TITLE
SSL cert support

### ISSUE THREAD

**Issue by samsch** [drgomesp/symfony-docker#8]
It would be great if symfony-docker supported an easy way of installing (or generating) SSL certs, and perhaps an option for always redirecting to HTTPS.

A first level solution might simply be pre-set names/directory(s) for the cert files.

A second stage solution might be a command for generating a CSR, and a self-signed cert for development.

Bonus: connect to [Let's Encrypt](https://letsencrypt.org/) and generate real certs.

**Comment by drgomesp** [comment]
@samsch thanks for the input, that is indeed something that would be amazing to have. I'll take a look into it and get back to you.

**Comment by drgomesp** [comment]
@samsch thanks for the input, that is indeed something that would be amazing to have. I'll take a look into it and get back to you.
