### ISSUE TITLE
Support PHP 7 in a different branch

### ISSUE THREAD

**Issue by drgomesp** [drgomesp/symfony-docker#9]
We need to support PHP 7 with all the same features in a different branch, so that users can choose which version they want to use for their projects.

**Comment by krzysztof-gzocha** [comment]
Maybe [extending docker-compose.yml file](https://docs.docker.com/compose/extends/) would be better than keep a track of different branch?
I mean we shall keep 1 branch, in which there will be `docker-compose.yml` file configured for PHP in version (for example) 5.x and `docker-compose.php7.yml` which will override just the PHP container with another one, but configured with version 7.
What do you think?

**Comment by drgomesp** [comment]
That's a good idea indeed. However, depending on the PHP version, we might have to adjust other dependencies and maybe change other containers (for example, memcached and elasticsearch containers might need different versions to work with PHP 7), although I'm not entirely sure at this point. For now I guess we can keep a different compose file.
